tunnel: your-cloudflared-json-file-name
credentials-file: your-cloudflared-json-file-full-path

ingress:
  - hostname: your-domain-name.your-domain-extension
    service: http://localhost:80
    originRequest:
      httpHostHeader: your-domain-name.your-domain-extension
      ipHeaders:
        - CF-Connecting-IP

  - hostname: www.your-domain-name.your-domain-extension
    service: http://localhost:80
    originRequest:
      httpHostHeader: your-domain-name.your-domain-extension
      ipHeaders:
        - CF-Connecting-IP

  - service: http_status:404