tunnel: template-cloudflared-json-file-name-with-no-extension
credentials-file: template-cloudflared-json-file-path

ingress:
  - hostname: template-domain-name
    service: http://127.0.0.1:80 (or something else)
  - service: http_status:404