[project]
name="kalaserver"
version="0-0-1"
kmake="project.kmake"

[references]
dir_kh="../kalaheaders"
ext_kh="external/kalaheaders"

[windows-sync]
kh_license=[ "${dir_kh}/LICENSE.md", "${ext_kh}/LICENSE.md", "copy" ]
kh_readme=[ "${dir_kh}/README.md", "${ext_kh}/README.md", "copy" ]
kh_include=[ "${dir_kh}/include", "${ext_kh}/include", "copy" ]

[windows-post-build-sync]
ks_bin_rel=[ "build/temp/release-windows/kalaserver.lib", "build/${version}/kalaserver.lib", "copy" ]
ks_bin_deb=[ "build/temp/debug-windows/kalaserverd.lib", "build/${version}/kalaserverd.lib", "copy" ]
ks_include=[ "include", "build/${version}/include", "copy" ]
ks_license=[ "LICENSE.md", "build/${version}/LICENSE.md", "copy" ]
ks_readme=[ "README.md", "build/${version}/README.md", "copy" ]
kh_stuff=[ "${ext_kh}", "build/${version}/kalaheaders", "copy" ]

[windows-gnu-sync]
kh_license=[ "${dir_kh}/LICENSE.md", "${ext_kh}/LICENSE.md", "copy" ]
kh_readme=[ "${dir_kh}/README.md", "${ext_kh}/README.md", "copy" ]
kh_include=[ "${dir_kh}/include", "${ext_kh}/include", "copy" ]

[windows-gnu-post-build-sync]
ks_bin_rel=[ "build/temp/release-windows-gnu/kalaserver-gnu.lib", "build/${version}/kalaserver-gnu.lib", "copy" ]
ks_bin_deb=[ "build/temp/debug-windows-gnu/kalaserver-gnud.lib", "build/${version}/kalaserver-gnud.lib", "copy" ]
ks_include=[ "include", "build/${version}/include", "copy" ]
ks_license=[ "LICENSE.md", "build/${version}/LICENSE.md", "copy" ]
ks_readme=[ "README.md", "build/${version}/README.md", "copy" ]
kh_stuff=[ "${ext_kh}", "build/${version}/kalaheaders", "copy" ]

[linux-sync]
kh_license=[ "${dir_kh}/LICENSE.md", "${ext_kh}/LICENSE.md", "copy" ]
kh_readme=[ "${dir_kh}/README.md", "${ext_kh}/README.md", "copy" ]
kh_include=[ "${dir_kh}/include", "${ext_kh}/include", "copy" ]

[linux-post-build-sync]
ks_bin_rel=[ "build/temp/release-linux/libkalaserver.a", "build/${version}/libkalaserver.a", "copy" ]
ks_bin_deb=[ "build/temp/debug-linux/libkalaserverd.a", "build/${version}/libkalaserverd.a", "copy" ]
ks_include=[ "include", "build/${version}/include", "copy" ]
ks_license=[ "LICENSE.md", "build/${version}/LICENSE.md", "copy" ]
ks_readme=[ "README.md", "build/${version}/README.md", "copy" ]
kh_stuff=[ "${ext_kh}", "build/${version}/kalaheaders", "copy" ]
